dist: bionic
language: python
python:
  - "3.6.9"
install:
  - sudo apt-get update
  - python3 -m pip install pip --upgrade pip
  - python3 -m pip install cython
  - python3 -m pip install numpy
  - python3 -m pip install pysam
  - python3 -m pip install https://github.com/timothyjamesbecker/somacx/releases/download/0.1.1/somacx-0.1.1.tar.gz
script:
  - generator.py -h
